/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAnnouncementRouteImport } from './routes/api/public/announcement'
import { Route as ApiPublicAppVersionRouteImport } from './routes/api/public/app-version'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiPublicItemLocksRouteImport } from './routes/api/public/item-locks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnnouncementRoute = ApiPublicAnnouncementRouteImport.update({
  id: '/api/public/announcement',
  path: '/api/public/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppVersionRoute = ApiPublicAppVersionRouteImport.update({
  id: '/api/public/app-version',
  path: '/api/public/app-version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicItemLocksRoute = ApiPublicItemLocksRouteImport.update({
  id: '/api/public/item-locks',
  path: '/api/public/item-locks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/announcement': typeof ApiPublicAnnouncementRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/item-locks': typeof ApiPublicItemLocksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/announcement': typeof ApiPublicAnnouncementRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/item-locks': typeof ApiPublicItemLocksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/announcement': typeof ApiPublicAnnouncementRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/item-locks': typeof ApiPublicItemLocksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/announcement'
    | '/api/public/app-version'
    | '/api/public/catalog'
    | '/api/public/item-locks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/announcement'
    | '/api/public/app-version'
    | '/api/public/catalog'
    | '/api/public/item-locks'
  id:
    | '__root__'
    | '/'
    | '/api/public/announcement'
    | '/api/public/app-version'
    | '/api/public/catalog'
    | '/api/public/item-locks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAnnouncementRoute: typeof ApiPublicAnnouncementRoute
  ApiPublicAppVersionRoute: typeof ApiPublicAppVersionRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
  ApiPublicItemLocksRoute: typeof ApiPublicItemLocksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/announcement': {
      id: '/api/public/announcement'
      path: '/api/public/announcement'
      fullPath: '/api/public/announcement'
      preLoaderRoute: typeof ApiPublicAnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-version': {
      id: '/api/public/app-version'
      path: '/api/public/app-version'
      fullPath: '/api/public/app-version'
      preLoaderRoute: typeof ApiPublicAppVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/item-locks': {
      id: '/api/public/item-locks'
      path: '/api/public/item-locks'
      fullPath: '/api/public/item-locks'
      preLoaderRoute: typeof ApiPublicItemLocksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAnnouncementRoute: ApiPublicAnnouncementRoute,
  ApiPublicAppVersionRoute: ApiPublicAppVersionRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
  ApiPublicItemLocksRoute: ApiPublicItemLocksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
